### ISSUE TITLE
Connecting a client to subpaths

### ISSUE THREAD

**Issue by dnna** [James-Frowen/SimpleWebTransport#10]
This may be more of a feature request than an issue. We want to host our game servers behind reverse proxies that rewrite the path, so that multiple servers can be hosted under the same domain under different paths. So for example, a game server URI could look like:

wss://xxx:123/ws/game-server/gs-c6431288-dd78-47a4-909a-cb085c416ea6

From what I saw, the C# `UriBuilder` supports a `Path` argument, but `SimpleWebTransport` does not use/expose it (we can only set hostname and port), so we can only connect the client to servers hosted at the root path of the domain.

Would that be something that can be added?

**Comment by James-Frowen** [comment]
The connect methods should already be able to take a `Uri`.

You can use `UriBuilder` to create your uri then use the `builder.Uri` property to get the uri to pass to SimpleWebTransport
