### ISSUE TITLE
Change the SendAll method parameter to take a ICollection<int> instead of List<int>

### ISSUE THREAD

**Issue by gmrodriguez124** [James-Frowen/SimpleWebTransport#12]
From the source, it doesn't seem there would be any detriment to changing this and would allow arrays and dict keys to be used directly.

```
public void SendAll(ICollection<int> connectionIds, ArraySegment<byte> source)
        {
            ArrayBuffer buffer = bufferPool.Take(source.Count);
            buffer.CopyFrom(source);
            buffer.SetReleasesRequired(connectionIds.Count);

            // make copy of array before for each, data sent to each client is the same
            foreach (int id in connectionIds)
                server.Send(id, buffer);
        }
```

**Comment by gmrodriguez124** [comment]
You're right, I didn't think of allocations because my use case isn't as affected by it. I agree, a second method would be most useful then to preserve the original better method but still allow for others, thanks!

I thought of IEnumerable but then the Count would be through linq

**Comment by James-Frowen** [comment]
added it here: https://github.com/James-Frowen/SimpleWebTransport/commit/28b6b25f7c1bf26cef04f5bae25377b485eec1ae

**Comment by gmrodriguez124** [comment]
Awesome, thanks!
