### ISSUE TITLE
dedicated server outside unity using C# console

### ISSUE THREAD

**Issue by jeffabner** [James-Frowen/SimpleWebTransport#7]
![image](https://github.com/James-Frowen/SimpleWebTransport/assets/33882384/fc577aef-3721-4aa4-b84c-ee0b0d2a78a4)
Here's an example of how the progress is going, but after connecting, it disconnects

**Comment by jeffabner** [comment]
[SimpleWebTransport] ERROR: [SimpleWebTransport] Connection closed before handshake
UnityEngine.Logger:Log (UnityEngine.LogType,object)
Mirror.SimpleWeb.Log:Error (string,bool) (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Common/Log.cs:93)
Mirror.SimpleWeb.ClientHandshake:TryHandshake (Mirror.SimpleWeb.Connection,System.Uri) (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Client/StandAlone/ClientHandshake.cs:53)
Mirror.SimpleWeb.WebSocketClientStandAlone:ConnectAndReceiveLoop (System.Uri) (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Client/StandAlone/WebSocketClientStandAlone.cs:68)
Mirror.SimpleWeb.WebSocketClientStandAlone/<>c__DisplayClass5_0:<Connect>b__0 () (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Client/StandAlone/WebSocketClientStandAlone.cs:36)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by jeffabner** [comment]
[SimpleWebTransport] WARN: [SimpleWebTransport] Failed Handshake with ws://localhost:7778/
UnityEngine.Logger:Log (UnityEngine.LogType,object)
Mirror.SimpleWeb.Log:Warn (string,bool) (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Common/Log.cs:82)
Mirror.SimpleWeb.WebSocketClientStandAlone:ConnectAndReceiveLoop (System.Uri) (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Client/StandAlone/WebSocketClientStandAlone.cs:71)
Mirror.SimpleWeb.WebSocketClientStandAlone/<>c__DisplayClass5_0:<Connect>b__0 () (at ./Library/PackageCache/com.james-frowen.simplewebtransport@1.6.4/Runtime/Client/StandAlone/WebSocketClientStandAlone.cs:36)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by jeffabner** [comment]
[unity-realtime-networking-server-main (2).zip](https://github.com/James-Frowen/SimpleWebTransport/files/12425764/unity-realtime-networking-server-main.2.zip)
Realtime Networking Server.sln

**Comment by jeffabner** [comment]
detail, I'm using mirror with the simpletransport socket that comes by default, using tank's example

**Comment by jeffabner** [comment]
https://assetstore.unity.com/packages/tools/network/realtime-tcp-udp-networking-231173

I'm basing myself on this project that has TCP and UDP

**Comment by James-Frowen** [comment]
2 things to make sure you are doing:
- call `ProcessMessageQueue` to process received message, best done on main thread before your main game loop
- send message to keep connection alive so it doesn't timeout. Mirror does this by sending ping/pong message every 2 seconds. You can also increase the timeout so you can send message less often.

**Comment by D4rWiNSS** [comment]
I am doing the same thing. I am creating the server in a c# console so this has helped me as welll thanks!

**Comment by predadorBR** [comment]
D4rWiNSS, did you manage to complete
