### ISSUE TITLE
Connecting to a simplewebserver via alternative client solution?

### ISSUE THREAD

**Issue by ZeoWorks** [James-Frowen/SimpleWebTransport#9]
Hi,
I'm currently connecting to the simplewebserver via this solution;
https://github.com/endel/NativeWebSocket

It works great, however after around 30 seconds the server disconnects.
To clarify, it seems like the simplewebserver is auto-kicking the client after 30 seconds.

Any reasons why you think this may be?

-Sean

**Comment by James-Frowen** [comment]
it disconnects connection if there are no messages within the `receiveTimeout`. you can either increase that timeout or send messages more often.

For example when SimpleWebTransport is used with Mirror, Mirror will send a Ping/Pong messages every few seconds (to keep time sync), and this also keeps the connections alive.

**Comment by ZeoWorks** [comment]
> it disconnects connection if there are no messages within the `receiveTimeout`. you can either increase that timeout or send messages more often.
> 
> For example when SimpleWebTransport is used with Mirror, Mirror will send a Ping/Pong messages every few seconds (to keep time sync), and this also keeps the connections alive.

Hi, I am sending a message every second but it still disconnects after 30 seconds (receive timeout is set to 5000).
A simple byte[1]{0}.  Thanks!

**Comment by James-Frowen** [comment]
Are you sending that 1 bytes message to/from both server and client? it is possible that NativeWebSocket  also has a timeout.

If that isn't it you might need to [enable logging](https://github.com/James-Frowen/SimpleWebTransport#logging-and-debugging) to try find out what is going wrong

**Comment by ZeoWorks** [comment]
Hi, Yes it is being sent to and from the server.
NativeWebSocket doesn't actually have a timeout, I've tested other node-based websocket servers without issue.

Upon enabling the debugger, we found this error occurs prior to disconnect after 30 seconds;
`ERROR: Invalid data from [Conn:1, endPoint:[::1]:63478]: Unexpected opcode 9`
![image](https://github.com/James-Frowen/SimpleWebTransport/assets/70698824/a55e28c4-439d-48ca-ab7d-8b97817df7ca)

**Comment by James-Frowen** [comment]
I think that is the ping opcode, SimpleWebTransport current doesn't have the ping/pong opcodes implemented, most websocket clients dont bother sending ping opcode so I havn't gotten around to adding it.

Is there a way to disable NativeWebSocket from sending the ping?

**Comment by James-Frowen** [comment]
Looking at NativeWebSocket it looks like it uses a similar jslib to SimpleWebTransport, so I assume it is the c# `ClientWebSocket` sending it. looking at the c# code, setting this should stop it sending ping  `clientWebSocket.Options.KeepAliveInterval = TimeSpan.Zero;`

**Comment by ZeoWorks** [comment]
Oh I believe you are correct, thanks!

`m_Socket.Options.KeepAliveInterval =TimeSpan.Zero;`

This did the trick.  Resolved.
